USE pos_system;

CREATE TABLE IF NOT EXISTS billing_payment_methods (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    type ENUM('bank_transfer', 'mobile_money', 'card', 'cash', 'other') NOT NULL DEFAULT 'bank_transfer',
    description VARCHAR(255) NULL,
    provider_name VARCHAR(150) NULL,
    account_name VARCHAR(150) NULL,
    account_number VARCHAR(150) NULL,
    checkout_url VARCHAR(255) NULL,
    supported_currencies_json LONGTEXT NULL,
    instructions TEXT NULL,
    requires_reference TINYINT(1) NOT NULL DEFAULT 0,
    requires_proof TINYINT(1) NOT NULL DEFAULT 0,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_billing_payment_methods_status (status),
    INDEX idx_billing_payment_methods_default (is_default)
) ENGINE=InnoDB;

ALTER TABLE billing_invoice_payments
    MODIFY COLUMN payment_method VARCHAR(80) NOT NULL DEFAULT 'bank_transfer',
    ADD COLUMN IF NOT EXISTS billing_payment_method_id BIGINT UNSIGNED NULL AFTER recorded_by_user_id,
    ADD INDEX idx_billing_invoice_payments_method (billing_payment_method_id),
    ADD CONSTRAINT fk_billing_invoice_payments_method FOREIGN KEY (billing_payment_method_id) REFERENCES billing_payment_methods(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS billing_payment_submissions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    billing_invoice_id BIGINT UNSIGNED NOT NULL,
    billing_payment_method_id BIGINT UNSIGNED NOT NULL,
    billing_invoice_payment_id BIGINT UNSIGNED NULL,
    submitted_by_user_id BIGINT UNSIGNED NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    status ENUM('submitted', 'approved', 'rejected', 'cancelled') NOT NULL DEFAULT 'submitted',
    payer_name VARCHAR(150) NULL,
    payer_email VARCHAR(150) NULL,
    customer_reference VARCHAR(150) NULL,
    gateway_reference VARCHAR(150) NULL,
    note TEXT NULL,
    review_note VARCHAR(255) NULL,
    proof_path VARCHAR(255) NULL,
    submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_billing_payment_submissions_company (company_id),
    INDEX idx_billing_payment_submissions_invoice (billing_invoice_id),
    INDEX idx_billing_payment_submissions_method (billing_payment_method_id),
    INDEX idx_billing_payment_submissions_status (status),
    INDEX idx_billing_payment_submissions_submitted_by (submitted_by_user_id),
    INDEX idx_billing_payment_submissions_reviewed_by (reviewed_by_user_id),
    CONSTRAINT fk_billing_payment_submissions_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_billing_payment_submissions_invoice FOREIGN KEY (billing_invoice_id) REFERENCES billing_invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_billing_payment_submissions_method FOREIGN KEY (billing_payment_method_id) REFERENCES billing_payment_methods(id) ON DELETE RESTRICT,
    CONSTRAINT fk_billing_payment_submissions_invoice_payment FOREIGN KEY (billing_invoice_payment_id) REFERENCES billing_invoice_payments(id) ON DELETE SET NULL,
    CONSTRAINT fk_billing_payment_submissions_submitted_by FOREIGN KEY (submitted_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_billing_payment_submissions_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

INSERT INTO billing_payment_methods (
    slug,
    name,
    type,
    description,
    provider_name,
    account_name,
    account_number,
    checkout_url,
    supported_currencies_json,
    instructions,
    requires_reference,
    requires_proof,
    is_default,
    status,
    sort_order,
    created_at,
    updated_at
) VALUES
    (
        'bank-transfer',
        'Bank Transfer',
        'bank_transfer',
        'Direct settlement into the platform billing bank account.',
        '',
        '',
        '',
        '',
        NULL,
        'Share the transfer reference exactly as it appears on your bank confirmation.',
        1,
        1,
        1,
        'active',
        10,
        NOW(),
        NOW()
    ),
    (
        'mobile-money',
        'Mobile Money',
        'mobile_money',
        'Wallet-to-wallet or merchant mobile money settlement.',
        '',
        '',
        '',
        '',
        NULL,
        'Use the platform mobile money details and submit the transaction reference after payment.',
        1,
        1,
        0,
        'active',
        20,
        NOW(),
        NOW()
    ),
    (
        'card-payment',
        'Card Payment',
        'card',
        'Card settlement using a hosted checkout link or terminal reference.',
        '',
        '',
        '',
        '',
        NULL,
        'If a hosted checkout link is configured, open it first and then submit the resulting reference here.',
        1,
        0,
        0,
        'active',
        30,
        NOW(),
        NOW()
    ),
    (
        'cash-settlement',
        'Cash Settlement',
        'cash',
        'Onsite cash settlement for enterprise or local collections.',
        '',
        '',
        '',
        '',
        NULL,
        'Use only when your platform team has approved physical settlement.',
        1,
        0,
        0,
        'inactive',
        40,
        NOW(),
        NOW()
    )
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    type = VALUES(type),
    description = VALUES(description),
    provider_name = VALUES(provider_name),
    account_name = VALUES(account_name),
    account_number = VALUES(account_number),
    checkout_url = VALUES(checkout_url),
    supported_currencies_json = VALUES(supported_currencies_json),
    instructions = VALUES(instructions),
    requires_reference = VALUES(requires_reference),
    requires_proof = VALUES(requires_proof),
    is_default = VALUES(is_default),
    status = VALUES(status),
    sort_order = VALUES(sort_order),
    updated_at = VALUES(updated_at);
