<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\AutomationController;
use App\Controllers\AuditLogController;
use App\Controllers\BillingController;
use App\Controllers\CustomerController;
use App\Controllers\DashboardController;
use App\Controllers\ExpenseController;
use App\Controllers\InventoryController;
use App\Controllers\NotificationController;
use App\Controllers\PosController;
use App\Controllers\ProductController;
use App\Controllers\PlatformBillingController;
use App\Controllers\PlatformController;
use App\Controllers\PurchaseOrderController;
use App\Controllers\ReportController;
use App\Controllers\ReturnController;
use App\Controllers\SalesController;
use App\Controllers\SettingsController;
use App\Controllers\StockTransferController;
use App\Controllers\SupplierController;
use App\Controllers\UserController;

$router->get('/', [DashboardController::class, 'home']);

$router->get('/login', [AuthController::class, 'showLogin'], ['guest']);
$router->post('/login', [AuthController::class, 'login'], ['guest']);
$router->get('/register', [AuthController::class, 'showRegister'], ['guest']);
$router->post('/register', [AuthController::class, 'register'], ['guest']);
$router->get('/verify-email', [AuthController::class, 'verifyEmail'], ['guest']);
$router->post('/verify-email/resend', [AuthController::class, 'resendVerification'], ['guest']);
$router->get('/forgot-password', [AuthController::class, 'showForgotPassword'], ['guest']);
$router->post('/forgot-password', [AuthController::class, 'sendResetLink'], ['guest']);
$router->get('/reset-password', [AuthController::class, 'showResetPassword'], ['guest']);
$router->post('/reset-password', [AuthController::class, 'resetPassword'], ['guest']);
$router->get('/platform/setup', [PlatformController::class, 'showSetup'], ['guest']);
$router->post('/platform/setup', [PlatformController::class, 'setup'], ['guest']);
$router->get('/platform/register', [PlatformController::class, 'showSetup'], ['guest']);
$router->post('/platform/register', [PlatformController::class, 'setup'], ['guest']);
$router->get('/automation/run', [AutomationController::class, 'run']);
$router->post('/logout', [AuthController::class, 'logout'], ['auth']);

$router->get('/platform', [PlatformController::class, 'index'], ['auth', 'platform_admin']);
$router->get('/platform/settings', [PlatformController::class, 'settings'], ['auth', 'platform_admin']);
$router->post('/platform/settings/update', [PlatformController::class, 'updateSettings'], ['auth', 'platform_admin']);
$router->post('/platform/automation/run', [AutomationController::class, 'manualRun'], ['auth', 'platform_admin']);
$router->get('/platform/billing', [PlatformBillingController::class, 'index'], ['auth', 'platform_admin']);
$router->post('/platform/billing/settings/update', [PlatformBillingController::class, 'updateSettings'], ['auth', 'platform_admin']);
$router->post('/platform/billing/cycle/run', [PlatformBillingController::class, 'runCycle'], ['auth', 'platform_admin']);
$router->post('/platform/billing/plans/create', [PlatformBillingController::class, 'createPlan'], ['auth', 'platform_admin']);
$router->post('/platform/billing/plans/update', [PlatformBillingController::class, 'updatePlan'], ['auth', 'platform_admin']);
$router->post('/platform/billing/payment-methods/create', [PlatformBillingController::class, 'createPaymentMethod'], ['auth', 'platform_admin']);
$router->post('/platform/billing/payment-methods/update', [PlatformBillingController::class, 'updatePaymentMethod'], ['auth', 'platform_admin']);
$router->post('/platform/billing/subscriptions/update', [PlatformBillingController::class, 'updateSubscription'], ['auth', 'platform_admin']);
$router->post('/platform/billing/invoices/create', [PlatformBillingController::class, 'createInvoice'], ['auth', 'platform_admin']);
$router->post('/platform/billing/invoices/payments/store', [PlatformBillingController::class, 'recordPayment'], ['auth', 'platform_admin']);
$router->post('/platform/billing/payments/submissions/approve', [PlatformBillingController::class, 'approvePaymentSubmission'], ['auth', 'platform_admin']);
$router->post('/platform/billing/payments/submissions/reject', [PlatformBillingController::class, 'rejectPaymentSubmission'], ['auth', 'platform_admin']);
$router->post('/platform/billing/invoices/status', [PlatformBillingController::class, 'updateInvoiceStatus'], ['auth', 'platform_admin']);
$router->get('/platform/billing/invoices/show', [PlatformBillingController::class, 'showInvoice'], ['auth', 'platform_admin']);
$router->get('/platform/admin-users', [PlatformController::class, 'adminUsers'], ['auth', 'platform_admin']);
$router->post('/platform/admin-users/create', [PlatformController::class, 'createPlatformAdmin'], ['auth', 'platform_admin']);
$router->post('/platform/admin-users/promote', [PlatformController::class, 'promotePlatformAdmin'], ['auth', 'platform_admin']);
$router->post('/platform/admin-users/status', [PlatformController::class, 'updatePlatformAdminStatus'], ['auth', 'platform_admin']);
$router->post('/platform/admin-users/revoke', [PlatformController::class, 'revokePlatformAdmin'], ['auth', 'platform_admin']);
$router->post('/platform/admin-users/resend-verification', [PlatformController::class, 'resendPlatformAdminVerification'], ['auth', 'platform_admin']);
$router->get('/platform/companies', [PlatformController::class, 'companies'], ['auth', 'platform_admin']);
$router->get('/platform/companies/show', [PlatformController::class, 'showCompany'], ['auth', 'platform_admin']);
$router->post('/platform/companies/defaults/reapply', [PlatformController::class, 'reapplyCompanyDefaults'], ['auth', 'platform_admin']);
$router->post('/platform/companies/status', [PlatformController::class, 'updateCompanyStatus'], ['auth', 'platform_admin']);
$router->post('/platform/companies/resend-owner-verification', [PlatformController::class, 'resendOwnerVerification'], ['auth', 'platform_admin']);
$router->post('/platform/companies/impersonate', [PlatformController::class, 'impersonateCompany'], ['auth', 'platform_admin']);
$router->post('/platform/impersonation/stop', [PlatformController::class, 'stopImpersonation'], ['auth']);

$router->get('/dashboard', [DashboardController::class, 'index'], ['auth', 'permission:view_dashboard']);
$router->get('/dashboard/live', [DashboardController::class, 'live'], ['auth', 'permission:view_dashboard']);
$router->post('/dashboard/email-summary', [DashboardController::class, 'emailDailySummary'], ['auth', 'permission:manage_reports', 'role:Super Admin,Admin,Manager']);

$router->get('/products', [ProductController::class, 'index'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->get('/products/suggest', [ProductController::class, 'suggest'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/products/categories', [ProductController::class, 'categories'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->get('/products/show', [ProductController::class, 'show'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->get('/products/create', [ProductController::class, 'create'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->get('/products/import', [ProductController::class, 'importForm'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->get('/products/import-template', [ProductController::class, 'importTemplate'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->post('/products/store', [ProductController::class, 'store'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->post('/products/import', [ProductController::class, 'import'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->post('/products/bulk-archive', [ProductController::class, 'bulkArchive'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->get('/products/edit', [ProductController::class, 'edit'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->post('/products/update', [ProductController::class, 'update'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->post('/products/delete', [ProductController::class, 'delete'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->post('/products/categories/store', [ProductController::class, 'storeCategory'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->post('/products/categories/update', [ProductController::class, 'updateCategory'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);
$router->post('/products/categories/delete', [ProductController::class, 'deleteCategory'], ['auth', 'permission:manage_products', 'role:Super Admin,Admin,Manager']);

$router->get('/inventory', [InventoryController::class, 'index'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/show', [InventoryController::class, 'show'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/adjust', [InventoryController::class, 'adjust'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/transfers', [StockTransferController::class, 'index'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/transfers/create', [StockTransferController::class, 'create'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/transfers/store', [StockTransferController::class, 'store'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/transfers/edit', [StockTransferController::class, 'edit'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/transfers/update', [StockTransferController::class, 'update'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/transfers/show', [StockTransferController::class, 'show'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/transfers/duplicate', [StockTransferController::class, 'duplicate'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/transfers/status', [StockTransferController::class, 'updateStatus'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/transfers/receive', [StockTransferController::class, 'receive'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/purchase-orders', [PurchaseOrderController::class, 'index'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/purchase-orders/create', [PurchaseOrderController::class, 'create'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/purchase-orders/store', [PurchaseOrderController::class, 'store'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/purchase-orders/edit', [PurchaseOrderController::class, 'edit'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/purchase-orders/update', [PurchaseOrderController::class, 'update'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/inventory/purchase-orders/show', [PurchaseOrderController::class, 'show'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/purchase-orders/duplicate', [PurchaseOrderController::class, 'duplicate'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/purchase-orders/status', [PurchaseOrderController::class, 'updateStatus'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/inventory/purchase-orders/receive', [PurchaseOrderController::class, 'receive'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);

$router->get('/suppliers', [SupplierController::class, 'index'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/suppliers/create', [SupplierController::class, 'create'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/suppliers/store', [SupplierController::class, 'store'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/suppliers/show', [SupplierController::class, 'show'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->get('/suppliers/edit', [SupplierController::class, 'edit'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/suppliers/update', [SupplierController::class, 'update'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);
$router->post('/suppliers/delete', [SupplierController::class, 'delete'], ['auth', 'permission:manage_inventory', 'role:Super Admin,Admin,Manager']);

$router->get('/customers', [CustomerController::class, 'index'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/customers/suggest', [CustomerController::class, 'suggest'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/customers/create', [CustomerController::class, 'create'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/customers/store', [CustomerController::class, 'store'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/customers/show', [CustomerController::class, 'show'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/customers/edit', [CustomerController::class, 'edit'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/customers/update', [CustomerController::class, 'update'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/customers/delete', [CustomerController::class, 'delete'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager']);
$router->post('/customers/groups/store', [CustomerController::class, 'storeGroup'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager']);
$router->post('/customers/groups/update', [CustomerController::class, 'updateGroup'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager']);
$router->post('/customers/groups/delete', [CustomerController::class, 'deleteGroup'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager']);
$router->post('/customers/credit/payment', [CustomerController::class, 'recordCreditPayment'], ['auth', 'permission:manage_customers', 'role:Super Admin,Admin,Manager,Cashier']);

$router->get('/sales', [SalesController::class, 'index'], ['auth', 'permission:manage_sales', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/sales/suggest', [SalesController::class, 'suggest'], ['auth', 'permission:manage_sales', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/sales/show', [SalesController::class, 'show'], ['auth', 'permission:manage_sales', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/sales/return', [SalesController::class, 'processReturn'], ['auth', 'permission:manage_sales', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/sales/void-request', [SalesController::class, 'requestVoid'], ['auth', 'permission:manage_sales', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/sales/void-review', [SalesController::class, 'reviewVoidRequest'], ['auth', 'permission:approve_voids', 'role:Super Admin,Admin,Manager']);
$router->post('/sales/void', [SalesController::class, 'void'], ['auth', 'permission:approve_voids', 'role:Super Admin,Admin,Manager']);

$router->get('/returns', [ReturnController::class, 'index'], ['auth', 'permission:manage_sales', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/returns/show', [ReturnController::class, 'show'], ['auth', 'permission:manage_sales', 'role:Super Admin,Admin,Manager,Cashier']);

$router->get('/expenses', [ExpenseController::class, 'index'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->get('/expenses/create', [ExpenseController::class, 'create'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->get('/expenses/show', [ExpenseController::class, 'show'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->get('/expenses/edit', [ExpenseController::class, 'edit'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->post('/expenses/store', [ExpenseController::class, 'store'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->post('/expenses/update', [ExpenseController::class, 'update'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->post('/expenses/delete', [ExpenseController::class, 'delete'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->post('/expenses/categories/store', [ExpenseController::class, 'storeCategory'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->post('/expenses/categories/update', [ExpenseController::class, 'updateCategory'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);
$router->post('/expenses/categories/delete', [ExpenseController::class, 'deleteCategory'], ['auth', 'permission:manage_expenses', 'role:Super Admin,Admin,Manager']);

$router->get('/reports', [ReportController::class, 'index'], ['auth', 'permission:manage_reports', 'role:Super Admin,Admin,Manager']);
$router->get('/reports/export', [ReportController::class, 'export'], ['auth', 'permission:manage_reports', 'role:Super Admin,Admin,Manager']);

$router->get('/users', [UserController::class, 'index'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->get('/users/create', [UserController::class, 'create'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->post('/users/store', [UserController::class, 'store'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->get('/users/show', [UserController::class, 'show'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->get('/users/edit', [UserController::class, 'edit'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->post('/users/update', [UserController::class, 'update'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->post('/users/toggle-status', [UserController::class, 'toggleStatus'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->post('/users/roles/permissions/update', [UserController::class, 'updateRolePermissions'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->get('/audit-logs', [AuditLogController::class, 'index'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);
$router->get('/audit-logs/export', [AuditLogController::class, 'export'], ['auth', 'permission:manage_users', 'role:Super Admin,Admin']);

$router->get('/settings', [SettingsController::class, 'index'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->get('/billing', [BillingController::class, 'index'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->get('/billing/invoices/show', [BillingController::class, 'showInvoice'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/billing/invoices/payments/submit', [BillingController::class, 'submitPayment'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/billing/invoices/payments/checkout', [BillingController::class, 'startCheckout'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->get('/billing/payments/callback', [BillingController::class, 'paymentCallback']);
$router->post('/billing/payments/paystack/webhook', [BillingController::class, 'paystackWebhook']);
$router->post('/billing/settings/update', [BillingController::class, 'updateSettings'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/update', [SettingsController::class, 'update'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/backups/create', [SettingsController::class, 'createBackup'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/backups/restore-kit', [SettingsController::class, 'createRestoreKit'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->get('/settings/backups/download', [SettingsController::class, 'downloadBackup'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/backups/restore', [SettingsController::class, 'restoreBackup'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/mail/test', [SettingsController::class, 'sendTestEmail'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/printer/test', [SettingsController::class, 'sendTestPrint'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/taxes/store', [SettingsController::class, 'storeTax'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/taxes/update', [SettingsController::class, 'updateTax'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/taxes/delete', [SettingsController::class, 'deleteTax'], ['auth', 'permission:manage_settings', 'role:Super Admin,Admin']);
$router->post('/settings/branches/store', [SettingsController::class, 'storeBranch'], ['auth', 'permission:manage_branches', 'role:Super Admin,Admin']);
$router->post('/settings/branches/update', [SettingsController::class, 'updateBranch'], ['auth', 'permission:manage_branches', 'role:Super Admin,Admin']);

$router->get('/notifications', [NotificationController::class, 'index'], ['auth']);
$router->get('/notifications/open', [NotificationController::class, 'open'], ['auth']);
$router->post('/notifications/read', [NotificationController::class, 'markAllRead'], ['auth']);
$router->post('/notifications/read-one', [NotificationController::class, 'markRead'], ['auth']);
$router->post('/notifications/unread-one', [NotificationController::class, 'markUnread'], ['auth']);

$router->get('/pos', [PosController::class, 'index'], ['auth', 'permission:access_pos', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/pos/catalog', [PosController::class, 'catalog'], ['auth', 'permission:access_pos', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/pos/hold', [PosController::class, 'hold'], ['auth', 'permission:access_pos', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/pos/checkout', [PosController::class, 'checkout'], ['auth', 'permission:access_pos', 'role:Super Admin,Admin,Manager,Cashier']);
$router->post('/pos/print', [PosController::class, 'printReceipt'], ['auth', 'permission:access_pos', 'role:Super Admin,Admin,Manager,Cashier']);
$router->get('/pos/receipt', [PosController::class, 'receipt'], ['auth', 'permission:access_pos', 'role:Super Admin,Admin,Manager,Cashier']);
